<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controls\ButtonControls\Button\Theme\" />
    <Folder Include="Controls\ButtonControls\DropDownButton\Theme\" />
    <Folder Include="Controls\ButtonControls\Images\" />
    <Folder Include="Controls\ButtonControls\SplitButton\Theme\" />
  </ItemGroup>

</Project>
